/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/game-engine/new": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["StartGameRequest"];
          "text/json": components["schemas"]["StartGameRequest"];
          "application/*+json": components["schemas"]["StartGameRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/game-engine/load": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoadGameRequest"];
          "text/json": components["schemas"]["LoadGameRequest"];
          "application/*+json": components["schemas"]["LoadGameRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/game-engine/event": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["GameEventRequest"];
          "text/json": components["schemas"]["GameEventRequest"];
          "application/*+json": components["schemas"]["GameEventRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    GameEventRequest: components["schemas"]["GameEventRequestPlayerReadyEventRequest"] | components["schemas"]["GameEventRequestPitcherInputEventRequest"] | components["schemas"]["GameEventRequestBatterInputEventRequest"];
    GameEventRequestBatterInputEventRequest: {
      /** @enum {string} */
      eventType?: "batter-input";
      swingType?: number;
      pitchType?: number | null;
      pitchLocationHorizontal?: number | null;
      pitchLocationVertical?: number | null;
      /** Format: uuid */
      gameId?: string;
    };
    GameEventRequestPitcherInputEventRequest: {
      /** @enum {string} */
      eventType?: "pitcher-input";
      pitchType?: number;
      pitchLocationHorizontal?: number;
      pitchLocationVertical?: number;
      /** Format: uuid */
      gameId?: string;
    };
    GameEventRequestPlayerReadyEventRequest: {
      /** @enum {string} */
      eventType?: "player-ready";
      /** Format: uuid */
      playerId?: string;
      /** Format: uuid */
      gameId?: string;
    };
    LoadGameRequest: {
      /** Format: uuid */
      gameId: string;
    };
    StartGameRequest: {
      /** Format: uuid */
      gameId?: string | null;
      homeTeam: components["schemas"]["TeamModel"];
      awayTeam: components["schemas"]["TeamModel"];
    };
    TeamModel: {
      id: string;
      playerIds?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
